### ISSUE TITLE
Add 2022 CFB Rosters

### ISSUE THREAD

**Issue by armstjc** [sportsdataverse/cfbfastR-data#2]
I need the 2022 CFB rosters for another sportsdataverse project.

**Comment by Kazink36** [comment]
Fall rosters don't start getting released until around late July or early August. We'll get them added once they pop up on collegefootballdata.com

**Comment by armstjc** [comment]
When should I expect this issue to be resolved?

**Comment by akeaswaran** [comment]
CFBData just added 2022 rosters last week: https://twitter.com/CFB_Data/status/1552076537259859970?s=20&t=kVdu0zzTDkwbFSt2W867dw

I assume all someone would have to do is just update the years that the rosters script runs for and it'll all work fine (other than for JMU's roster not being posted).
